services:
  app:
    image: maxplushchreif/maximo-oauth2-app
    container_name: maximo-oauth2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OAUTH_CLIENT_ID=maximo-client
      - OAUTH_CLIENT_SECRET=CHANGE_ME_STRONG_SECRET
    restart: unless-stopped

